### ISSUE TITLE
The `isce2` package is incompatible with newer versions of `numpy`

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3-isce2#14]
I get the following error:

```
  File "/home/jth/code/hyp3-isce2/src/hyp3_isce2/topsapp.py", line 175, in run_topsapp_burst
    insar.run()
  File "/home/jth/jth-apps/miniconda3/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/iscesys/Component/Application.py", line 142, in run
    exitStatus = self._processSteps()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/jth/jth-apps/miniconda3/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/iscesys/Component/Application.py", line 405, in _processSteps
    result = func(*pargs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jth/jth-apps/miniconda3/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/isceobj/TopsProc/Factories.py", line 40, in __call__
    return self.method(self.other, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jth/jth-apps/miniconda3/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/isceobj/TopsProc/runFineResamp.py", line 387, in runFineResamp
    azCarrPoly, dpoly = secondary.estimateAzimuthCarrierPolynomials(secondaryBurst, offset = -1.0 * offset)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jth/jth-apps/miniconda3/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/isceobj/Sensor/TOPS/TOPSSwathSLCProduct.py", line 285, in estimateAzimuthCarrierPolynomials
    x = np.arange(0, burst.numberOfSamples,xstep,dtype=np.int)
                                                       ^^^^^^
  File "/home/jth/jth-apps/miniconda3/envs/hyp3-isce2/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```

The issue is resolved by including the following lines in `environment.yml`:

```
- python>=3.8,<=3.10
- numpy<1.20
```

Numpy must be pinned to `<1.20` because of the `isce2` incompatibility, and Python must be pinned to `<=3.10` because the older version of Numpy is incompatible with Python 3.11.

However, I have `isce2` version `2.6.1` installed, and I just noticed that `2.6.2` is available from https://anaconda.org/conda-forge/isce2. So perhaps the newer version of `isce2` resolves the `numpy` issue.

TODO:

- [x] Determine if installing `isce2` version `2.6.2` solves the issue.
- [x] If not, pin `python` and `numpy` as shown above.
- [x] Unpin those packages when the issue is fixed in `isce2`

**Comment by forrestfwilliams** [comment]
Based on the [2.6.2 release notes](https://github.com/isce-framework/isce2/releases/tag/v2.6.2) it looks like this problem should be fixed. Maybe we should pin `isce2` instead?

**Comment by jtherrmann** [comment]
The problem is not fixed, we're still seeing the same error with the following versions installed:

```
numpy 1.24.2
isce2 2.6.2
```

**Comment by jtherrmann** [comment]
I opened https://github.com/isce-framework/isce2/issues/696 to hopefully get this fixed.
